name: Semgrep Analysis
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Python, pip, Semgrep y prospector-html
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install semgrep prospector2html

      - name: Semgrep scan
        run: |
          semgrep scan --config="p/default" --sarif --output=report.sarif --metrics=off
          semgrep scan --config="p/default" --json --output semgrep.json

      - name: Generar reporte HTML con prospector-html
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
